### ISSUE TITLE
UI: Milestones

### ISSUE THREAD

**Issue by PhilippFaber** [PhilippFaber/sg-drill#10]
An gewissen Punkten im Spiel (Übergang von einer Erdschicht zur nächsten z.B.) sollen Milestones mit kurzen Textpassagen eingeblendet werden.

- [ ] Das Spiel wird pausiert, während die Einblendung aktiv ist.
- [ ] Man sieht Z.M.
- [ ] Es wird eine Textbox mit einem motivierenden Text eingeblendet (hier noch entscheiden ob der Text fest vorgeschrieben sein soll oder zufällig aus ein paar Optionen ausgewählt wird).
- [ ] Mit einem Button-press wird die Textbox wieder ausgeblendet und das Spiel geht weiter
